model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/vicuna-13b
      api_base: http://host.docker.internal:20080/v1
      api_key: None
  - model_name: text-embedding-ada-002
    litellm_params:
      model: openai/sentence-luke
      api_base: http://host.docker.internal:40080/v1
      api_key: None
  - model_name: vicuna-13b
    litellm_params:
      model: openai/vicuna-13b
      api_base: http://host.docker.internal:20080/v1
      api_key: None
  - model_name: karakuri-8x7b
    litellm_params:
      model: openai/karakuri-8x7b
      api_base: http://host.docker.internal:20080/v1
      api_key: None
  - model_name: karakuri-70b
    litellm_params:
      model: openai/karakuri-70b
      api_base: http://host.docker.internal:30080/v1
      api_key: None
  - model_name: sentence-luke
    litellm_params:
      model: openai/sentence-luke
      api_base: http://host.docker.internal:40080/v1
      api_key: None